language: node_js

node_js:
  - "stable"

script: echo "npm test temporarily disabled"

cache:
  directories:
    - ./client/node_modules
      ./node_modules

before_script:
  - npm install
# script:
# - npm --cwd ./client npm run format

# linter:
#    - npm --cwd ./client npm run lint
# deploy:
#   provider: heroku
#   api_key:
#     secure: 02fd9fe8-39cd-481e-abf9-09fd627f4ae1
#   app: final-project-online-store
#   on:
